### ISSUE TITLE
NEM Update 0.6.82. Lower Fees is still not applied.

### ISSUE THREAD

**Issue by him0** [nikhiljha/nem-api#1]
[NEM Update 0.6.82. Lower Fees and New API - Blog Posts - NEM Forum](https://forum.nem.io/t/nem-update-0-6-82-lower-fees-and-new-api/2979)

The fee setting is wrong ,because this update is still not applied to this package.

**Comment by nikhiljha** [comment]
Waiting for people to tell me if I did it right - then I will push the fix.

**Comment by nikhiljha** [comment]
Fixed.
